package life.majiang.community.community.mapper;

import java.util.List;
import life.majiang.community.community.model.UserLocalAuth;
import life.majiang.community.community.model.UserLocalAuthExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserLocalAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_local_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    long countByExample(UserLocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_local_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int deleteByExample(UserLocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_local_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int deleteByPrimaryKey(Integer authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_local_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int insert(UserLocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_local_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int insertSelective(UserLocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_local_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    List<UserLocalAuth> selectByExampleWithRowbounds(UserLocalAuthExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_local_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    List<UserLocalAuth> selectByExample(UserLocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_local_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    UserLocalAuth selectByPrimaryKey(Integer authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_local_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserLocalAuth record, @Param("example") UserLocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_local_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int updateByExample(@Param("record") UserLocalAuth record, @Param("example") UserLocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_local_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int updateByPrimaryKeySelective(UserLocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_local_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int updateByPrimaryKey(UserLocalAuth record);
}