package life.majiang.community.community.mapper;

import java.util.List;
import life.majiang.community.community.model.UserThirdAuth;
import life.majiang.community.community.model.UserThirdAuthExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserThirdAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_third_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    long countByExample(UserThirdAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_third_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int deleteByExample(UserThirdAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_third_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int deleteByPrimaryKey(Integer authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_third_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int insert(UserThirdAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_third_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int insertSelective(UserThirdAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_third_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    List<UserThirdAuth> selectByExampleWithRowbounds(UserThirdAuthExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_third_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    List<UserThirdAuth> selectByExample(UserThirdAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_third_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    UserThirdAuth selectByPrimaryKey(Integer authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_third_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserThirdAuth record, @Param("example") UserThirdAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_third_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int updateByExample(@Param("record") UserThirdAuth record, @Param("example") UserThirdAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_third_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int updateByPrimaryKeySelective(UserThirdAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_third_auth
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    int updateByPrimaryKey(UserThirdAuth record);
}