package life.majiang.community.community.model;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.token
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_info
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    private String userInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.avatar_url
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mobile
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    private Integer mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.token
     *
     * @return the value of users.token
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.token
     *
     * @param token the value for users.token
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_info
     *
     * @return the value of users.user_info
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public String getUserInfo() {
        return userInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_info
     *
     * @param userInfo the value for users.user_info
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public void setUserInfo(String userInfo) {
        this.userInfo = userInfo == null ? null : userInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.avatar_url
     *
     * @return the value of users.avatar_url
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.avatar_url
     *
     * @param avatarUrl the value for users.avatar_url
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mobile
     *
     * @return the value of users.mobile
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public Integer getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mobile
     *
     * @param mobile the value for users.mobile
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }
}