package life.majiang.community.community.model;

public class UserAuthRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth_rel.id
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth_rel.user_id
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth_rel.auth_id
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    private Integer authId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth_rel.auth_type
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    private String authType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth_rel.id
     *
     * @return the value of user_auth_rel.id
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth_rel.id
     *
     * @param id the value for user_auth_rel.id
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth_rel.user_id
     *
     * @return the value of user_auth_rel.user_id
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth_rel.user_id
     *
     * @param userId the value for user_auth_rel.user_id
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth_rel.auth_id
     *
     * @return the value of user_auth_rel.auth_id
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public Integer getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth_rel.auth_id
     *
     * @param authId the value for user_auth_rel.auth_id
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public void setAuthId(Integer authId) {
        this.authId = authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth_rel.auth_type
     *
     * @return the value of user_auth_rel.auth_type
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth_rel.auth_type
     *
     * @param authType the value for user_auth_rel.auth_type
     *
     * @mbg.generated Fri Oct 08 07:36:31 CST 2021
     */
    public void setAuthType(String authType) {
        this.authType = authType == null ? null : authType.trim();
    }
}